# Generated by Django 5.0.6 on 2024-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuelo', models.CharField(max_length=20)),
                ('aerolinea', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('pasajeros', models.IntegerField()),
            ],
        ),
    ]
